/// <reference types="cypress"/>
describe('template spec', () => {
  beforeEach('Belépés a login oldalra', () => {
    cy.visit('http://127.0.0.1:5500/Duna%20Mozi/Frontend/HTML/bejel.html')
  })
  const joAdminEmail='havlagb1@gmail.com'
  const joAdminjelszo= "Admin"
  it('Belépés jó adatokkal admin felületre',()=>{
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a dolgozó feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új dolgozó').click()
    cy.url().should('include', 'reg.html')
  })
  it('Admin ki tud-e lépni a dolgozó feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új dolgozó').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a dolgozó módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Dolgozó módosítása').click()
    cy.url().should('include', 'dolgozomod.html')
  })
  it('Admin ki tud-e lépni a dolgozó módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Dolgozó módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a film feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.url().should('include', 'ujfilm.html')
  })
  it('Admin ki tud-e lépni a film feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a film módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.url().should('include', 'filmmod.html')
  })
  it('Admin ki tud-e lépni a film módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a esemény feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új esemény').click()
    cy.url().should('include', 'esemenyekreg.html')
  })
  it('Admin ki tud-e lépni a esemény feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új esemény').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a esemény módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Esemény módosítása').click()
    cy.url().should('include', 'esemenymod.html')
  })
  it('Admin ki tud-e lépni a esemény módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Esemény módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a vetítés feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új vetítés').click()
    cy.url().should('include', 'vetitesreg.html')
  })
  it('Admin ki tud-e lépni a vetítés feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új vetítés').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
  it('Admin be tud-e lépni a vetítés módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Vetítés módosítása').click()
    cy.url().should('include', 'vetitesmod.html')
  })
  it('Admin ki tud-e lépni a vetítés módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Vetítés módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'admin.html')
  })
})