/// <reference types="cypress"/>
describe('template spec', () => {
  beforeEach('Belépés a login oldalra', () => {
    cy.visit('http://127.0.0.1:5500/Duna%20Mozi/Frontend/HTML/bejel.html')
  })
  const joEmail='gibsz.elek2005@gmail.com'
  const jojelszo= "Adambatyam"
  it('Belépés jó adatokkal alkalmazott felületre',()=>{
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a film feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.url().should('include', 'ujfilm.html')
  })
  it('Alkalmazott ki tud-e lépni a film feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a film módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.url().should('include', 'filmmod.html')
  })
  it('Alkalmazott ki tud-e lépni a flim módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a esemény feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új esemény').click()
    cy.url().should('include', 'esemenyekreg.html')
  })
  it('Alkalmazott ki tud-e lépni a esemény feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új esemény').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a esemény módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Esemény módosítása').click()
    cy.url().should('include', 'esemenymod.html')
  })
  it('Alkalmatott ki tud-e lépni a esemény módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Esemény módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a vetítés feltöltő oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új vetítés').click()
    cy.url().should('include', 'vetitesreg.html')
  })
  it('Alkalmazott ki tud-e lépni a vetítés feltöltő oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új vetítés').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
  it('Alkalmazott be tud-e lépni a vetítés módosítása oldalra',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Vetítés módosítása').click()
    cy.url().should('include', 'vetitesmod.html')
  })
  it('Alkalmazott ki tud-e lépni a vetítés módosítása oldalról',()=>{
    cy.wait(5000)
    cy.get('input[type=email]').type(joEmail)
    cy.get('input[type=password').type(jojelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Vetítés módosítása').click()
    cy.get('button').contains('Vissza az előző oldalra').click()
    cy.url().should('include', 'alkalmazott.html')
  })
})