/// <reference types="cypress"/>
describe('template spec', () => {
  beforeEach('Belépés a login oldalra', () => {
    cy.visit('http://127.0.0.1:5500/Duna%20Mozi/Frontend/HTML/bejel.html')
  })
  const joAdminEmail = 'havlagb1@gmail.com'
  const joAdminjelszo = "Admin"

  const tesztfilmcim = 'Cypress film'
  const tesztfilmcim2 = 'Cypress teszt film'
  const rossztesztfilmcim = 'Cypress@film'
  const tesztfoszereplo = 'Cypress Jóska mint Tesztelő'
  const rossztesztfoszereplo = 'Cypress@Jóska mint Te$ztel¤'
  const tesztleitas = 'Cypress Jóska tesztel'
  const rossztesztleitas = 'Cypress_JóskaŁtesztel'
  const teszthossz = '120'
  const tesztkorhatar = '6'
  const tesztkategoria='Akció'
  const tesztlink='https://cdn.pixabay.com/photo/2021/09/03/15/14/woman-6596029_1280.jpg'
  const rossztesztlink='Cypress_Joska_profelkep.jpg'

  it('Film regisztráció teszt jó adatokkal', () => {
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(0).type(tesztfilmcim)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Sikeres film feltöltés') })
  })
  it('Film modósítása teszt jó adatokkal', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim)
    cy.get('input[type=text]').eq(0).type(tesztfilmcim2)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Sikeres film módosítása') })
  })
  it('Film regisztráció teszt hiányos adatokkal (nincs névmegadás)', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Töltsön ki minden mezőt!') })
  })
  it('Film módosítása teszt hiányos adatokkal (nincs névmegadás)', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Töltsön ki minden mezőt!') })
  })
  it('Film regisztráció teszt regex-nek nem megfelelő címmel', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(0).type(rossztesztfilmcim)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás cím vagy leírás! A film címe vagy leírása nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film regisztráció teszt regex-nek nem megfelelő leírással', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(0).type(tesztfilmcim)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(rossztesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás cím vagy leírás! A film címe vagy leírása nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film regisztráció teszt regex-nek nem megfelelő szereplőnév', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(0).type(tesztfilmcim)
    cy.get('input[type=text]').eq(1).type(rossztesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hiba a szereplők nevénél! Nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film regisztráció teszt regex-nek nem megfelelő linkel', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Új film').click()
    cy.get('input[type=text]').eq(0).type(tesztfilmcim)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(rossztesztlink)
    cy.get('button').contains('Film feltöltése').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás link! Nem engedéjezett karaktert tartalmaz, vagy nem felel meg a link formai követelményének!') })
  })
  it('Film modósítása teszt regex-nek nem megfelelő címmel', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('input[type=text]').eq(0).type(rossztesztfilmcim)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás cím vagy leírás! A film címe vagy leírása nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film modósítása teszt regex-nek nem megfelelő leírással', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('input[type=text]').eq(0).type(tesztfilmcim2)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(rossztesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás cím vagy leírás! A film címe vagy leírása nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film modósítása teszt regex-nek nem megfelelő szereplőnév', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('input[type=text]').eq(0).type(tesztfilmcim2)
    cy.get('input[type=text]').eq(1).type(rossztesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(tesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hiba a szereplők nevénél! Nem engedéjezett karaktert tartalmaz!') })
  })
  it('Film modósítása teszt regex-nek nem megfelelő linkkel', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail)
    cy.get('input[type=password]').type(joAdminjelszo)
    cy.get('button').contains('Bejelentkezés').click()
    cy.get('button').contains('Film módosítása').click()
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('input[type=text]').eq(0).type(tesztfilmcim2)
    cy.get('input[type=text]').eq(1).type(tesztfoszereplo)
    cy.get('input[type=text]').eq(2).type(tesztleitas)
    cy.get('input[type=number]').eq(0).type(teszthossz)
    cy.get('input[type=number]').eq(1).type(tesztkorhatar)
    cy.get('select').eq(1).select(tesztkategoria)
    cy.get('input[type=text]').eq(3).type(rossztesztlink)
    cy.get('button').contains('Film módosítása').click()
    cy.on('window:alert', (str) => { expect(str).to.equal('Hibás link! Nem engedéjezett karaktert tartalmaz, vagy nem felel meg a link formai követelményének!') })
  })
  it('Film törlése teszt jó adatokkal', () => {
    cy.wait(5000)
    cy.get('input[type=email]').type(joAdminEmail);
    cy.get('input[type=password]').type(joAdminjelszo);
    cy.get('button').contains('Bejelentkezés').click();
    cy.get('button').contains('Film módosítása').click();
    cy.get('select').eq(0).select(tesztfilmcim2)
    cy.get('button').contains('Film törlése').click();
    cy.on('window:alert', (str) => { expect(str).to.equal('Sikeres film törlése') })
  })
})
